name: Build and Release PortAudio

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install CMake
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

    - name: Install Visual Studio Build Tools
      run: |
        choco install visualstudio2019buildtools --version=16.11.3

    - name: Build PortAudio
      run: |
        git clone https://github.com/PortAudio/portaudio.git
        cd portaudio
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release

    - name: List Build Output
      run: |
        cd portaudio/build/Release
        dir

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: portaudio-binaries
        path: portaudio/build/Release/*

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: portaudio-binaries
        path: release-files

    - name: Generate Release Tag
      id: tag_generator
      run: |
        # Generate timestamp-based tag (vYYYYMMDD.HHMMSS)
        TAG="v$(date -u '+%Y%m%d.%H%M%S')"
        echo "Generated tag: $TAG"
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag_generator.outputs.tag }}
        name: PortAudio Build ${{ steps.tag_generator.outputs.tag }}
        body: "Automated build of PortAudio binaries"
        files: |
          release-files/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
